ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'INSTRUCTOR_COURSE_CREATED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'INSTRUCTOR_CURRICULUM_ADDED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'INSTRUCTOR_CURRICULUM_UPDATED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'INSTRUCTOR_PAYOUT_REQUESTED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'INSTRUCTOR_ANNOUNCEMENT_POSTED';
